---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(scales)
library(DT)
library(plotly)
library(knitr)
data <- readRDS("complaints.rds")


```

Column {data-width=650}
-----------------------------------------------------------------------

### Number of complaints by state

```{r}
data %>% group_by(state) %>% count() %>% arrange(desc(n)) %>% ungroup %>% mutate(prop=percent(n/sum(n))) %>% datatable

```

Column {data-width=350}
-----------------------------------------------------------------------

### Pie chart of timely response rate

```{r}
data %>% group_by(timely_response) %>% count() %>% arrange(desc(n)) %>% ungroup %>% mutate(prop=percent(n/sum(n))) %>% plot_ly(labels=~timely_response, values=~n,type="pie")

```

### Heatmap of submitted via and product

```{r}
data %>% group_by(submitted_via,product) %>% count() %>% plot_ly(x=~submitted_via, y=~product,z=~n,type="heatmap")

```


